language: go

go:
  - 1.11

before_script:
  - make prepare

script:
  - make deploy

env:
  global:
    secure: "KX+C9KkMB/rlYPxanHLnZQ7lnkAo6e6adFcm/WouyPVDKr+TWyowytjPw5ZLeS8QeCzQwvGOSxWPzkZFJ4Mkdy4+8gq0WCH/EPeuqPdRpAHCYvxUSNo6zGBI8JFQzRK9dvupGJrIMwfp5zkss6NqcBcBSFmsa0b4inQcn+GM9Rs="
